# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions
# If env does not exist run the follwoing on Azure Cloud Shell: https://portal.azure.com/#cloudshell/
# az containerapp env create --name lion-containerapp-env --resource-group rg-lion-app --location westeurope

name: Build and deploy Python project to Azure Function App - lion-orchestrator
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './' # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.12' # set this to the python version to use (supports 3.6, 3.7, 3.8)


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies to .python_packages
        run: pip install -r requirements.txt -t .python_packages/lib/site-packages/

      - name: Zip function app for deployment
        run: |
          zip -r release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    env:
      AZURE_SQL_USER: ${{ secrets.AZURE_SQL_USER }}
      AZURE_SQL_PASS: ${{ secrets.AZURE_SQL_PASS }}
      AZURE_SQL_SERVER: ${{ secrets.AZURE_SQL_SERVER }}
      AZURE_SQL_DB: ${{ secrets.AZURE_SQL_DB }}
      DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      APP_NAME: ${{ vars.APP_NAME }}
      APP_ENV: ${{ vars.APP_ENV }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
      CLIENT_ID: ${{ secrets.AZUREAPPSERVICE_CLIENTID_327141F8816D460997B41D94CEC1131C }}
      TENANT_ID: ${{ secrets.AZUREAPPSERVICE_TENANTID_0F4AEE2C55A24FEFAF0DBA4037D3A2E4 }}
      SUBSCRIPTION_ID: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_42FEBC4B4FE94E1BAF8B57D899F0E3A2 }}
      AZURE_LION_APP_CLIENT_SECRET: ${{ secrets.AZURE_LION_APP_CLIENT_SECRET }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip
          rm release.zip
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ env.CLIENT_ID }}
          tenant-id: ${{ env.TENANT_ID}}
          subscription-id: ${{ env.SUBSCRIPTION_ID }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: ${{ env.APP_NAME }}
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      - name: Configure Azure Function App Settings
        run: |
          az functionapp config appsettings set \
            --name "$APP_NAME" \
            --resource-group "$AZURE_RESOURCE_GROUP" \
            --settings \
              AZURE_SQL_USER="$AZURE_SQL_USER" \
              AZURE_SQL_PASS="$AZURE_SQL_PASS" \
              AZURE_SQL_SERVER="$AZURE_SQL_SERVER" \
              AZURE_SQL_DB="$AZURE_SQL_DB" \
              AZURE_RESOURCE_GROUP="$AZURE_RESOURCE_GROUP" \
              AZURE_STORAGE_CONNECTION_STRING="$AZURE_STORAGE_CONNECTION_STRING" \
              APP_NAME="$APP_NAME" \
              DOCKER_IMAGE="$DOCKER_IMAGE" \
              AZURE_SUBSCRIPTION_ID="$AZURE_SUBSCRIPTION_ID" \
              APP_ENV="$APP_ENV"

